"""Harmonisation des relations et corrections to_dict

Revision ID: e1e80bc4f81e
Revises: 35eaf0514c4e
Create Date: 2026-05-29 16:09:38.306540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1e80bc4f81e'
down_revision = '35eaf0514c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False))

    # ### end Alembic commands ###
